### PR TITLE
Refactor src, minor optimization and add doc

### PR DESCRIPTION
**Pull request by NobodyXu**
Signed-off-by: Jiahao XU <Jiahao_XU@outlook.com>

### CODE REVIEW

**Comment by passcod** [comment]
tbh I can't really effectively review this, I'm really not familiar with the codebase. would you be okay to have the review requirement dropped here so you can merge yourself? there's no real point getting reviews that aren't going to be more than "nothing jumps out at me"

**Comment by NobodyXu** [comment]
\

> tbh I can't really effectively review this, I'm really not familiar with the codebase. would you be okay to have the review requirement dropped for this repo so you can merge yourself? there's no real point getting reviews that aren't going to be more than "nothing jumps out at me and the build passes"

Yes, I'm fine with this or appointing me to be the admin of this repo.

**Comment by passcod** [comment]
done! sorry that took a while

**Comment by NobodyXu** [comment]
> done! sorry that took a while

Thank you!

**Pull request merged**
